=begin
#Up API

#The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

require 'date'
require 'time'

module OpenapiClient
  class WebhookDeliveryStatusEnum
    DELIVERED = "DELIVERED".freeze
    UNDELIVERABLE = "UNDELIVERABLE".freeze
    BAD_RESPONSE_CODE = "BAD_RESPONSE_CODE".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = WebhookDeliveryStatusEnum.constants.select { |c| WebhookDeliveryStatusEnum::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #WebhookDeliveryStatusEnum" if constantValues.empty?
      value
    end
  end
end
