# -*- encoding: utf-8 -*-

=begin
#Up API

#The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "up_banking/version"

Gem::Specification.new do |s|
  s.name        = "up_banking"
  s.version     = UpBankingClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Ben Richardson"]
  s.email       = [""]
  s.homepage    = "https://github.com/ben-gy/up-banking"
  s.summary     = "Unofficial Ruby gem for the Up Banking API"
  s.description = "Unofficial Ruby gem for the Up Banking API"
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.4"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
