=begin
#Up API

#The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'date'
require 'time'

module UpBankingClient
  class AccountTypeEnum
    SAVER = "SAVER".freeze
    TRANSACTIONAL = "TRANSACTIONAL".freeze

    def self.all_vars
      @all_vars ||= [SAVER, TRANSACTIONAL].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if AccountTypeEnum.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #AccountTypeEnum"
    end
  end
end
