=begin
#Up API

#The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for UpBankingClient::AccountsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountsApi' do
  before do
    # run before each test
    @api_instance = UpBankingClient::AccountsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountsApi' do
    it 'should create an instance of AccountsApi' do
      expect(@api_instance).to be_instance_of(UpBankingClient::AccountsApi)
    end
  end

  # unit tests for accounts_get
  # List accounts
  # Retrieve a paginated list of all accounts for the currently authenticated user. The returned list is paginated and can be scrolled by following the &#x60;prev&#x60; and &#x60;next&#x60; links where present. 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page_size The number of records to return in each page. 
  # @option opts [AccountTypeEnum] :filter_account_type The type of account for which to return records. This can be used to filter Savers from spending accounts. 
  # @option opts [OwnershipTypeEnum] :filter_ownership_type The account ownership structure for which to return records. This can be used to filter 2Up accounts from Up accounts. 
  # @return [ListAccountsResponse]
  describe 'accounts_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for accounts_id_get
  # Retrieve account
  # Retrieve a specific account by providing its unique identifier. 
  # @param id The unique identifier for the account. 
  # @param [Hash] opts the optional parameters
  # @return [GetAccountResponse]
  describe 'accounts_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
