=begin
#Up API

#The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for UpBankingClient::UtilityEndpointsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UtilityEndpointsApi' do
  before do
    # run before each test
    @api_instance = UpBankingClient::UtilityEndpointsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UtilityEndpointsApi' do
    it 'should create an instance of UtilityEndpointsApi' do
      expect(@api_instance).to be_instance_of(UpBankingClient::UtilityEndpointsApi)
    end
  end

  # unit tests for util_ping_get
  # Ping
  # Make a basic ping request to the API. This is useful to verify that authentication is functioning correctly. On authentication success an HTTP &#x60;200&#x60; status is returned. On failure an HTTP &#x60;401&#x60; error response is returned. 
  # @param [Hash] opts the optional parameters
  # @return [PingResponse]
  describe 'util_ping_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
