=begin
#Up API

#The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.1.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/account_resource'
require 'openapi_client/models/account_resource_attributes'
require 'openapi_client/models/account_resource_links'
require 'openapi_client/models/account_resource_relationships'
require 'openapi_client/models/account_resource_relationships_transactions'
require 'openapi_client/models/account_resource_relationships_transactions_links'
require 'openapi_client/models/account_type_enum'
require 'openapi_client/models/cashback_object'
require 'openapi_client/models/category_resource'
require 'openapi_client/models/category_resource_attributes'
require 'openapi_client/models/category_resource_relationships'
require 'openapi_client/models/category_resource_relationships_children'
require 'openapi_client/models/category_resource_relationships_children_data'
require 'openapi_client/models/category_resource_relationships_parent'
require 'openapi_client/models/category_resource_relationships_parent_data'
require 'openapi_client/models/create_webhook_request'
require 'openapi_client/models/create_webhook_response'
require 'openapi_client/models/error_object'
require 'openapi_client/models/error_object_source'
require 'openapi_client/models/error_response'
require 'openapi_client/models/get_account_response'
require 'openapi_client/models/get_category_response'
require 'openapi_client/models/get_transaction_response'
require 'openapi_client/models/get_webhook_response'
require 'openapi_client/models/hold_info_object'
require 'openapi_client/models/list_accounts_response'
require 'openapi_client/models/list_accounts_response_links'
require 'openapi_client/models/list_categories_response'
require 'openapi_client/models/list_tags_response'
require 'openapi_client/models/list_transactions_response'
require 'openapi_client/models/list_webhook_delivery_logs_response'
require 'openapi_client/models/list_webhooks_response'
require 'openapi_client/models/money_object'
require 'openapi_client/models/ping_response'
require 'openapi_client/models/ping_response_meta'
require 'openapi_client/models/round_up_object'
require 'openapi_client/models/tag_input_resource_identifier'
require 'openapi_client/models/tag_resource'
require 'openapi_client/models/transaction_resource'
require 'openapi_client/models/transaction_resource_attributes'
require 'openapi_client/models/transaction_resource_relationships'
require 'openapi_client/models/transaction_resource_relationships_account'
require 'openapi_client/models/transaction_resource_relationships_account_data'
require 'openapi_client/models/transaction_resource_relationships_tags'
require 'openapi_client/models/transaction_resource_relationships_tags_data'
require 'openapi_client/models/transaction_resource_relationships_tags_links'
require 'openapi_client/models/transaction_status_enum'
require 'openapi_client/models/update_transaction_tags_request'
require 'openapi_client/models/webhook_delivery_log_resource'
require 'openapi_client/models/webhook_delivery_log_resource_attributes'
require 'openapi_client/models/webhook_delivery_log_resource_attributes_request'
require 'openapi_client/models/webhook_delivery_log_resource_attributes_response'
require 'openapi_client/models/webhook_delivery_log_resource_relationships'
require 'openapi_client/models/webhook_delivery_log_resource_relationships_webhook_event'
require 'openapi_client/models/webhook_delivery_log_resource_relationships_webhook_event_data'
require 'openapi_client/models/webhook_delivery_status_enum'
require 'openapi_client/models/webhook_event_callback'
require 'openapi_client/models/webhook_event_resource'
require 'openapi_client/models/webhook_event_resource_attributes'
require 'openapi_client/models/webhook_event_resource_relationships'
require 'openapi_client/models/webhook_event_resource_relationships_transaction'
require 'openapi_client/models/webhook_event_resource_relationships_transaction_data'
require 'openapi_client/models/webhook_event_resource_relationships_webhook'
require 'openapi_client/models/webhook_event_resource_relationships_webhook_data'
require 'openapi_client/models/webhook_event_type_enum'
require 'openapi_client/models/webhook_input_resource'
require 'openapi_client/models/webhook_input_resource_attributes'
require 'openapi_client/models/webhook_resource'
require 'openapi_client/models/webhook_resource_attributes'
require 'openapi_client/models/webhook_resource_relationships'

# APIs
require 'openapi_client/api/accounts_api'
require 'openapi_client/api/categories_api'
require 'openapi_client/api/tags_api'
require 'openapi_client/api/transactions_api'
require 'openapi_client/api/utility_endpoints_api'
require 'openapi_client/api/webhooks_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
