=begin
#Up API

#The Up API gives you programmatic access to your balances and transaction data. You can request past transactions or set up webhooks to receive real-time events when new transactions hit your account. It’s new, it’s exciting and it’s just the beginning. 

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.2.0

=end

# Common files
require 'up_banking/api_client'
require 'up_banking/api_error'
require 'up_banking/version'
require 'up_banking/configuration'

# Models
require 'up_banking/models/account_resource'
require 'up_banking/models/account_resource_attributes'
require 'up_banking/models/account_resource_attributes_balance'
require 'up_banking/models/account_resource_links'
require 'up_banking/models/account_resource_relationships'
require 'up_banking/models/account_resource_relationships_transactions'
require 'up_banking/models/account_resource_relationships_transactions_links'
require 'up_banking/models/account_type_enum'
require 'up_banking/models/cashback_object'
require 'up_banking/models/cashback_object_amount'
require 'up_banking/models/category_input_resource_identifier'
require 'up_banking/models/category_resource'
require 'up_banking/models/category_resource_attributes'
require 'up_banking/models/category_resource_relationships'
require 'up_banking/models/category_resource_relationships_children'
require 'up_banking/models/category_resource_relationships_children_data_inner'
require 'up_banking/models/category_resource_relationships_parent'
require 'up_banking/models/category_resource_relationships_parent_data'
require 'up_banking/models/create_webhook_request'
require 'up_banking/models/create_webhook_request_data'
require 'up_banking/models/create_webhook_response'
require 'up_banking/models/create_webhook_response_data'
require 'up_banking/models/error_object'
require 'up_banking/models/error_object_source'
require 'up_banking/models/error_response'
require 'up_banking/models/get_account_response'
require 'up_banking/models/get_account_response_data'
require 'up_banking/models/get_category_response'
require 'up_banking/models/get_category_response_data'
require 'up_banking/models/get_transaction_response'
require 'up_banking/models/get_transaction_response_data'
require 'up_banking/models/get_webhook_response'
require 'up_banking/models/get_webhook_response_data'
require 'up_banking/models/hold_info_object'
require 'up_banking/models/hold_info_object_amount'
require 'up_banking/models/hold_info_object_foreign_amount'
require 'up_banking/models/list_accounts_response'
require 'up_banking/models/list_accounts_response_links'
require 'up_banking/models/list_categories_response'
require 'up_banking/models/list_tags_response'
require 'up_banking/models/list_transactions_response'
require 'up_banking/models/list_webhook_delivery_logs_response'
require 'up_banking/models/list_webhooks_response'
require 'up_banking/models/money_object'
require 'up_banking/models/ownership_type_enum'
require 'up_banking/models/ping_response'
require 'up_banking/models/ping_response_meta'
require 'up_banking/models/round_up_object'
require 'up_banking/models/round_up_object_amount'
require 'up_banking/models/round_up_object_boost_portion'
require 'up_banking/models/tag_input_resource_identifier'
require 'up_banking/models/tag_resource'
require 'up_banking/models/transaction_resource'
require 'up_banking/models/transaction_resource_attributes'
require 'up_banking/models/transaction_resource_attributes_amount'
require 'up_banking/models/transaction_resource_attributes_cashback'
require 'up_banking/models/transaction_resource_attributes_foreign_amount'
require 'up_banking/models/transaction_resource_attributes_hold_info'
require 'up_banking/models/transaction_resource_attributes_round_up'
require 'up_banking/models/transaction_resource_relationships'
require 'up_banking/models/transaction_resource_relationships_account'
require 'up_banking/models/transaction_resource_relationships_account_data'
require 'up_banking/models/transaction_resource_relationships_category'
require 'up_banking/models/transaction_resource_relationships_category_links'
require 'up_banking/models/transaction_resource_relationships_tags'
require 'up_banking/models/transaction_resource_relationships_tags_data_inner'
require 'up_banking/models/transaction_resource_relationships_tags_links'
require 'up_banking/models/transaction_resource_relationships_transfer_account'
require 'up_banking/models/transaction_resource_relationships_transfer_account_data'
require 'up_banking/models/transaction_status_enum'
require 'up_banking/models/update_transaction_category_request'
require 'up_banking/models/update_transaction_category_request_data'
require 'up_banking/models/update_transaction_tags_request'
require 'up_banking/models/webhook_delivery_log_resource'
require 'up_banking/models/webhook_delivery_log_resource_attributes'
require 'up_banking/models/webhook_delivery_log_resource_attributes_request'
require 'up_banking/models/webhook_delivery_log_resource_attributes_response'
require 'up_banking/models/webhook_delivery_log_resource_relationships'
require 'up_banking/models/webhook_delivery_log_resource_relationships_webhook_event'
require 'up_banking/models/webhook_delivery_log_resource_relationships_webhook_event_data'
require 'up_banking/models/webhook_delivery_status_enum'
require 'up_banking/models/webhook_event_callback'
require 'up_banking/models/webhook_event_callback_data'
require 'up_banking/models/webhook_event_resource'
require 'up_banking/models/webhook_event_resource_attributes'
require 'up_banking/models/webhook_event_resource_relationships'
require 'up_banking/models/webhook_event_resource_relationships_transaction'
require 'up_banking/models/webhook_event_resource_relationships_transaction_data'
require 'up_banking/models/webhook_event_resource_relationships_webhook'
require 'up_banking/models/webhook_event_resource_relationships_webhook_data'
require 'up_banking/models/webhook_event_type_enum'
require 'up_banking/models/webhook_input_resource'
require 'up_banking/models/webhook_input_resource_attributes'
require 'up_banking/models/webhook_resource'
require 'up_banking/models/webhook_resource_attributes'
require 'up_banking/models/webhook_resource_relationships'

# APIs
require 'up_banking/api/accounts_api'
require 'up_banking/api/categories_api'
require 'up_banking/api/tags_api'
require 'up_banking/api/transactions_api'
require 'up_banking/api/utility_endpoints_api'
require 'up_banking/api/webhooks_api'

module UpBankingClient
  class << self
    # Customize default settings for the SDK using block.
    #   UpBankingClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
